An option to sort sections
Chilipp/autodocsumm pull request #93
Opened 2023-12-28 22:20 UTC by funkyfuture

this is a solution for the proposal in #90.

from a user perspective, i'd actually rather prefer to simply provide a `True` to achieve simple alphabetical sorting. shall i extend to this?

should i add an example where a dict with weights to define the order is used?

i also did some occasional modernization of code as one may consider it. are these changes okay?

2023-12-28 22:25 UTC, Chilipp commented
Awesome! Thanks :smiley: I'll have a closer look tomorrow. But yes, I agree that a simple `True` option would be a good idea :+1:

2024-01-04 08:31 UTC, Chilipp requested changes
hey @funkyfuture! thanks a lot for the input here! The changes look great! I only have two minor suggestions for the docs, but otherwise I am happy to merge this when you are done here and make a new release :+1:

2024-01-04 08:31 UTC, Chilipp commented on docs/conf_settings.rst
> +       autodocsumm_section_sorter = lambda title: sections_order.index(title)
```suggestion
   .. code-block:: python

       sections_order = ("Public methods", "Attributes", "Private methods")
       autodocsumm_section_sorter = lambda title: sections_order.index(title)
```

2024-01-04 08:31 UTC, Chilipp commented on docs/conf_settings.rst
> +       autodocsumm_section_sorter = lambda title: sections_weights.get(title, 0)
```suggestion
   .. code-block:: python

       section_weights = {"Attributes": 100, "Constructors": -100}
       autodocsumm_section_sorter = lambda title: sections_weights.get(title, 0)
```

2024-01-04 08:32 UTC, Chilipp commented
please let me know @funkyfuture if there is anything else from your side or if I can merge this PR as it is

2024-01-04 10:49 UTC, funkyfuture commented
thanks for the feedback. i'm happy with the solution as it is.

2024-01-04 12:28 UTC, Chilipp approved these changes
awesome! :partying_face:

2024-01-04 12:29 UTC, merged